[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "pip install -r advanced_model/requirements.txt",
  "pnpm install --frozen-lockfile --prefer-offline --include=dev"
]



[phases.build]
cmds = [
  "pnpm run build",
  "echo '--- build done, listing dist ---'",
  "ls -la dist || true",
  "ls -la dist/server || true",
  "ls -la dist/server/routes || true"
]

[phases.start]
cmds = ["pnpm start"]
